import Head from 'next/head'
import Image from 'next/image'
import Declaraciones from '@/engine/declaraciones'
import UserCheck from '@/engine/userCheck'
import { useState } from 'react'


export default function Home() {
  const [usersArray, setUsersArray] = useState({
    array: [{
      nombre: 'moet', password: '1234', permisions: {
        console: true,
        logistica: true,
        configuracion: true
      }, appPermisions: {
        inicio: true,
        clientes: true,
        servicios: true,
        vehiculos: true,
        personalLogistico: true,
        rutas: true,
        novedades: true,
        historial: true,
        requerimientos: true,
        vendedores: true,
      }, avatar: {
        withPhoto: false,
        url: ''
      },
      status: 'registered',


    }, {
      nombre: 'oscar', password: '1234', permisions: {
        console: false,
        logistica: true,
        empresas: true,
        vendedores: true
      },
      appPermisions: {
        inicio: true,
        clientes: true,
        servicios: true,
        vehiculos: true,
        personalLogistico: true,
        rutas: false,
        novedades: false,
        historial: false,
        requerimientos: false,
        vendedores: false,
      },
      avatar: {
        withPhoto: true,
        url: '/image/oscar.png'
      }

    }]
  }
  )
  return (
    <>
      <Head>
        <title>Biosepticos App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'div-main'}>
        <UserCheck usersArray={usersArray} setUsersArray={setUsersArray} />
      </main>
    </>
  )
}
