import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'


export default function Home() {
    const mensajes = ['Hola Meli', 'Sabes algo....', 'Lo que te digo no es mentira, no quiero ser otro contigo', 'Me haces mucho bien', 'ademas....', 'te lo confesare', 'Me gustas mucho', 'te quiero en mi vida, como amiga  siempre', 'y ojala tambien como amantes, lo demas dejemoslo al destino', 'pase muy rico en amaga', ' Quieres que te haga un Blog, asi el mundo sabra lo mamacita que eres XD']
    const [usersArray, setUsersArray] = useState(0)

    setInterval(() => {
        if (mensajes.length > usersArray) {
            const index = usersArray

            setUsersArray(index + 1)
        }

    }, 5000);
    return (
        <>
            <Head>
                <title>Para Meli</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={'div-main'}>
                <div className='melipage'>
                    <p>{mensajes[usersArray]}</p>
                </div>

            </main>
        </>
    )
}
