
"use client"
import { useEffect, useMemo, useRef, useState ,useCallback } from "react";
import { useLoadScript, GoogleMap, MarkerF } from "@react-google-maps/api";
import { Loader } from "@googlemaps/js-api-loader";


export {
    DEFAULT_BBOX,
    randomPointInFenceBBox,
    assignVehiclesToFences,
    centerFromBox,
    rand,
    choice,
    pad,
    buildLatBandFencesVertices,
    buildLonBandFencesVertices,
    buildGridFencesVertices,
    stripUltimoNumero,
    buildFencesByMode,
    _placesSingleton,
    ensurePlacesServices,
    toPolygonPathAndStyle,
    BRANDS,
    COLORS,
    DIM_OPTS,
    PAYLOAD_KG_RANGE,
    letters,
    randomPlate,
    buildFleet,
    rnd,
    libraries,
    mapOptions,
    isInFence,
    fenceForPoint,
    fenceCenterFromBBox,
    vehicleCaps,
    canFitCargoInVehicle,
    FenceLabels,
    assignObrasToFleetByGeofence,
    assignVehiclesToFencesCenter,
    MapGeofences,
    MapVehicles,
    MapGeocercasConRutas,
    LS_IMPORTADAS_KEY,
    syncImportadasToLS,
    readExcelToRows,
    pick,
    rowToObraInput,
    obraHasCoords,
    assignObrasToFences,
    hasCoords,
    roundN,
    simularCargaLaminas,
    actualizarZonasObras
}